import Head from "next/head";
import React from "react";
import MainFooter from "../footer/main-footer";
import MainNavigation from "../header/main-navigation";

interface Props {
  children: React.ReactNode;
  title?: string;
}

const MainLayout: React.FC<Props> = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title || "Jumpstart"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-rows-[auto_1fr_auto] min-h-screen">
        <MainNavigation />
        <main>{children}</main>
        <MainFooter />
      </div>
    </>
  );
};

export default MainLayout;
